/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package softwaretema3;

/**
 *
 * @author Eliel Novelo
 */
public class JFRPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JFRPrincipal
     */
    public JFRPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        JMNLineal = new javax.swing.JMenu();
        JMIJacobi = new javax.swing.JMenuItem();
        JMINewton = new javax.swing.JMenuItem();
        JMNPuntoF = new javax.swing.JMenu();
        JMNPuntoFijo = new javax.swing.JMenuItem();
        JMNewton = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Metodo");

        JMNLineal.setText("Ecuaciones lineales");

        JMIJacobi.setText("Jacobi");
        JMIJacobi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMIJacobiActionPerformed(evt);
            }
        });
        JMNLineal.add(JMIJacobi);

        JMINewton.setText("Gauss Seidel");
        JMINewton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMINewtonActionPerformed(evt);
            }
        });
        JMNLineal.add(JMINewton);

        jMenu1.add(JMNLineal);

        JMNPuntoF.setText("Ecuaciones No lineales");

        JMNPuntoFijo.setText("Punto Fijo");
        JMNPuntoFijo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMNPuntoFijoActionPerformed(evt);
            }
        });
        JMNPuntoF.add(JMNPuntoFijo);

        JMNewton.setText("Newton");
        JMNewton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMNewtonActionPerformed(evt);
            }
        });
        JMNPuntoF.add(JMNewton);

        jMenu1.add(JMNPuntoF);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JMIJacobiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMIJacobiActionPerformed
        dlgJacobi vnt = new dlgJacobi(this,true);
        vnt.setVisible(true);
    }//GEN-LAST:event_JMIJacobiActionPerformed

    private void JMINewtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMINewtonActionPerformed
        dlgGaussSeidel vtn = new dlgGaussSeidel(this, true);
        vtn.setVisible(true);
    }//GEN-LAST:event_JMINewtonActionPerformed

    private void JMNPuntoFijoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMNPuntoFijoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JMNPuntoFijoActionPerformed

    private void JMNewtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMNewtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JMNewtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFRPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFRPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFRPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFRPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFRPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem JMIJacobi;
    private javax.swing.JMenuItem JMINewton;
    private javax.swing.JMenu JMNLineal;
    private javax.swing.JMenu JMNPuntoF;
    private javax.swing.JMenuItem JMNPuntoFijo;
    private javax.swing.JMenuItem JMNewton;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
